const fs=require('fs');
const text=fs.readFileSync('/Users/mickyatakilt/Desktop/Probate SC - Sheet1 (1).csv','utf8');
function ltParseCSV(text){var rows=[],cur=[],val='',inQ=false;for(var i=0;i<text.length;i++){var c=text[i];if(inQ){if(c==='"'){if(text[i+1]==='"'){val+='"';i++;}else inQ=false;}else val+=c;}else{if(c==='"')inQ=true;else if(c===','){cur.push(val);val='';}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;cur.push(val);rows.push(cur);cur=[];val='';}else val+=c;}}if(val!==''||cur.length){cur.push(val);rows.push(cur);}return rows.filter(function(r){return r.some(function(x){return String(x).trim()!=='';});});}
function pbColIdx(header,names){var norm=function(s){return String(s||'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');};var H=header.map(norm);for(var n=0;n<names.length;n++){var i=H.indexOf(norm(names[n]));if(i>=0)return i;}return -1;}
function pbIsLegendRow(nm,ph,ad){var L=function(s){return String(s||'').trim().toLowerCase();};var n=L(nm),p=L(ph),a=L(ad);if(/^owner\s*\d*\s*first name$/.test(n))return true;if(/^wireless(\s*\d+)?$/.test(p)||p==='phone number'||p==='phone')return true;if(a==='property_address'||a==='source'||a==='address'||a==='street address')return true;return false;}
function pbParseReplace(text){var rows=ltParseCSV(text||'');if(rows.length<2)return{rows:[]};var header=rows[0];var iFirst=pbColIdx(header,['First Name','First','firstname']);var iLast=pbColIdx(header,['Last Name','Last','lastname']);var iName=pbColIdx(header,['Name','Full Name','Owner Name','personal_rep','PR Name']);var iPhone=pbColIdx(header,['Phone Number','Phone','Cell','Mobile','Wireless 1','Wireless','Phone 1']);var iAddr=pbColIdx(header,['Address','Mailing Address','personal_rep_address','Property Address','Street Address','Street','Source']);var out=[];for(var r=1;r<rows.length;r++){var row=rows[r];var nm=iName>=0?(row[iName]||'').trim():[iFirst>=0?(row[iFirst]||'').trim():'',iLast>=0?(row[iLast]||'').trim():''].filter(Boolean).join(' ');var ph=iPhone>=0?(row[iPhone]||'').trim():'';var ad=iAddr>=0?(row[iAddr]||'').trim():'';if(!nm&&!ph&&!ad)continue;if(pbIsLegendRow(nm,ph,ad))continue;out.push({name:nm,phone:ph,address:ad});}return{rows:out};}
const p=pbParseReplace(text);
console.log('ROWS FOUND:',p.rows.length);
console.log('first row now:',p.rows[0]);
console.log('a LAST,FIRST row:',p.rows.find(r=>r.name.includes(',')));
console.log('legend present?',p.rows.some(r=>/owner 1 first name/i.test(r.name)||/^wireless/i.test(r.phone)));
